services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: agenda-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://agenda_user:agenda_password@postgres:5432/agenda_db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    networks:
      - agenda-network

  postgres:
    image: postgres:16-alpine
    container_name: agenda-db
    environment:
      POSTGRES_DB: agenda_db
      POSTGRES_USER: agenda_user
      POSTGRES_PASSWORD: agenda_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - agenda-network

  adminer:
    image: adminer:latest
    container_name: agenda-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - agenda-network

volumes:
  postgres_data:
    driver: local

networks:
  agenda-network:
    driver: bridge
